const assert = require('node:assert/strict');
const M = require('./model.js');
const quote = { supplier: 'A', unitPrice: 100, discount: 10, tax: 18, freight: 20, days: 10, warranty: 6 };
const settings = { quantity: 2, maxDays: 14, minWarranty: 0, weights: [60, 25, 15] };
const one = M.analyze([quote], settings);
assert.equal(one.rows[0].total, 232.4);
assert.equal(one.rows[0].score, 100);
const limited = M.analyze([quote, { ...quote, supplier: 'B', days: 20, unitPrice: 1 }], settings);
assert.equal(limited.eligibleCount, 1);
assert.equal(limited.rows[0].supplier, 'A');
assert.equal(limited.rows[1].score, null);
assert.equal(M.analyze([quote, { ...quote, supplier: 'B' }], settings).leaders.length, 2);
assert.throws(() => M.analyze([quote], { ...settings, weights: [0, 0, 0] }));
assert.throws(() => M.analyze([{ ...quote, unitPrice: '' }], settings));
assert.throws(() => M.analyze([quote, { ...quote, supplier: 'a' }], settings));
const escaped = { ...quote, supplier: 'Acme, "Supply"' };
assert.equal(M.parseCSV(M.csv([escaped], M.headers))[0].supplier, escaped.supplier);
assert.ok(M.csv([{ supplier: '=SUM(A1)' }], ['supplier']).includes("'=SUM"));
assert.equal(M.analyze([quote], { ...settings, minWarranty: 12 }).eligibleCount, 0);
console.log('Calculation, eligibility, ties, validation and CSV checks passed.');
